FROM logstash:5.5
# COPY logstash_settings/ /usr/share/logstash/config/
# COPY logstash_pipeline/ /usr/share/logstash/pipeline/
# COPY logstash-output-kafka-7.0.3.gem /opt/
# RUN logstash-plugin install /opt/logstash-output-kafka-7.0.3.gem

RUN logstash-plugin install --no-verify logstash-output-kafka

COPY logstash_pipeline/logstash.conf /config-dir/

CMD ["-f", "/config-dir/logstash.conf"]

